#ifndef FTDI_VERSION_INTERNAL_H
#define FTDI_VERSION_INTERNAL_H

#define MAJOR_VERSION 1
#define MINOR_VERSION 2

#define FTDI_MAJOR_VERSION MAJOR_VERSION
#define FTDI_MINOR_VERSION MINOR_VERSION
#define FTDI_MICRO_VERSION 0

const char FTDI_VERSION_STRING[] = "1.2";
const char FTDI_SNAPSHOT_VERSION[] = "unknown";

#endif
